Repository googleapis/nodejs-notebooks, pull requests merged in 2020-11, with the labels that each got.

#15 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: api: notebooks, cla: yes

#5 chore: start tracking obsolete files
  synth.metadata
Labels: api: notebooks, cla: yes, context: full

#16 fix: export type for NotebookServiceClient
  protos/google/cloud/notebooks/v1beta1/instance.proto
  protos/google/cloud/notebooks/v1beta1/service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1beta1/notebook_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: notebooks, cla: yes, context: full

#22 fix(browser): check for fetch on window
  protos/protos.json
  src/v1beta1/notebook_service_client.ts
  synth.metadata
Labels: api: notebooks, cla: yes, context: partial

#24 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full
